### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by DOH-WLD0303** [marygracemoesta/R-User-Guide#3]
Hi all,

First of all, I want to say thank you for the excellent guide that you've put together! I'm working through it and wanted to help improve where possible by pointing out issues in the documentation. I'll post further issues as I come across them.

https://github.com/marygracemoesta/R-User-Guide/blob/master/Developing_on_Databricks/package_management.md#cluster-scope

The link for `user defined functions` is broken in the section I've linked to above. I'm not quite sure if it was intended to point internally or externally.

Thanks!
Logan.

**Comment by RafiKurlansik** [comment]
Sorry for the very delayed response!  So glad you are benefiting from this, and thank you for filing the issue.  There are some broken links, but I don't think we are going to fix them.  We are planning on revamping this entire documentation this year, and that will become the new guide. :)
